sudo: required
language: java
jdk: openjdk8
install: true

cache:
  directories:
    - "$HOME/.cache"
addons:
  sonarcloud:
    organization: "anasabdelrahman-github" # the key of the org you chose at step #3
    token:
      secure: "ebCbx2/XkNrPrpHdYje8uOiuLMUPx7mqZmkJhcbueiMsjoAMMx4m3k09GRKZj0fTYo4mdGlA8lU3SwoLwCf3sj8MiseiKxsjVXymbIXWj+06zMGebBzL+jbH8jZTLAc2CzbH1xYRgEVUhFOpYV4P6rzVinYwnOM4Xa5GATm9XKrYJmfHStFVhp0yfr/N1sw6EEBanjykXMXdapaLFsySqiwIf5NCaGTABz3TKc+vxzzr6TJaR4HCx4wQ9CIx3c9v+vTujJru96txZ5mLmIA2NyOk3yjNxAtxvxqvBI3U+l84blvQgj0Nefv5zuPrRUguCIWhv6aYvhJU5GH1fTfw90gMG00sab7+IuH2NzEYAA0E3tA865V3JLdOj+fJWJdSysfksI4BtgBgC0CmsuZNdx72c8pR/xEvyaFJkupQ7HEpqy/I+mIQ3B1fKUPHsGOr0tvwuV1PfoGia+jrQorvao0jAXQST0IuuFtLW9dmEd6GycAPilptgleHoeQpwA80wq9uhmA/gvkg1zFykB3O6BQxPY8r9du6m0HShc0SSfiAyA3exmbks0CfW0vK86XjUGkQthS8QQ11FVTLn47cslrD7jmblQlawUkta5a6+kunTFx3vykYS8ptYmTRzOmqXTeILuP0e+FqsD4LjIwTr1RAg4KX/qxpGi8BrLKqz3Y="

  # encrypted value of your token

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

script:
#  - cd vmc-dashboard
#  - docker build -t $DOCKER_USERNAME/vmc-dashboard:$TRAVIS_BUILD_ID .
#  - docker push $DOCKER_USERNAME/vmc-dashboard:$TRAVIS_BUILD_ID

  - cd vmc-config
  - mvn clean install
  - sonar-scanner
  - docker build -t $DOCKER_USERNAME/vmc-config:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/vmc-config:$TRAVIS_BUILD_ID

  - cd ../vmc-registry
  - mvn clean install
  - sonar-scanner
  - docker build -t $DOCKER_USERNAME/vmc-registry:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/vmc-registry:$TRAVIS_BUILD_ID

  - cd ../vmc-gateway
  - mvn clean install
  - sonar-scanner
  - docker build -t $DOCKER_USERNAME/vmc-gateway:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/vmc-gateway:$TRAVIS_BUILD_ID

  - cd ../vmc-monitoring
  - mvn clean install
  - sonar-scanner
  - docker build -t $DOCKER_USERNAME/vmc-monitoring:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/vmc-monitoring:$TRAVIS_BUILD_ID

#  - cd ../vmc-turbine-stream
#  - mvn clean install
#  - sonar-scanner
#  - docker build -t $DOCKER_USERNAME/vmc-turbine-stream:$TRAVIS_BUILD_ID .
#  - docker push $DOCKER_USERNAME/vmc-turbine-stream:$TRAVIS_BUILD_ID

  - cd ../vmc-vehicle
  - mvn clean install
  - sonar-scanner
  - docker build -t $DOCKER_USERNAME/vmc-vehicle:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/vmc-vehicle:$TRAVIS_BUILD_ID

  - cd ../vmc-customer
  - mvn clean install
  - sonar-scanner
  - docker build -t $DOCKER_USERNAME/vmc-customer:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/vmc-customer:$TRAVIS_BUILD_ID

  - cd ../vmc-status
  - mvn clean install
  - sonar-scanner
  - docker build -t $DOCKER_USERNAME/vmc-status:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/vmc-status:$TRAVIS_BUILD_ID

  - cd ../vmc-simulator
  - mvn clean install
  - sonar-scanner
  - docker build -t $DOCKER_USERNAME/vmc-simulator:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/vmc-simulator:$TRAVIS_BUILD_ID

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

    #deploy:
    #- provider: s3
    #access_key_id: $AWS_ACCESS_KEY
    #secret_access_key: $AWS_SECRET_KEY
    #local_dir: dpl_cd_upload
    #skip_cleanup: true
    #on: $DOCKER_USERNAME/vmc-dashboard
    #repo: travis-ci/cat-party
    #bucket: codepipeline-us-west-2-746906032635

    #- provider: codedeploy
    #access_key_id: $AWS_ACCESS_KEY
    #secret_access_key: $AWS_SECRET_KEY
    #bucket: codepipeline-us-west-2-746906032635
    #key: vmc-dashboard
    #application: DemoApp1
    #deployment_group: DemoAppServices1
    #on: 
  #- repo: $DOCKER_USERNAME/vmc-dashboard */
